name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Download and set up Poppler
      run: |
        # Download Poppler
        curl -LO https://github.com/oschwartz10612/poppler-windows/releases/download/v23.01.0-0/Release-23.01.0-0.zip
        
        # Unzip the downloaded file
        powershell -Command "Expand-Archive -Path 'Release-23.01.0-0.zip' -DestinationPath '.'"
        
        # Set Poppler path environment variable
        echo "poppler path:" $(pwd)/Release-23.01.0-0/poppler-23.01.0/Library/bin
        echo $(pwd)/Release-23.01.0-0/poppler-23.01.0/Library/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Your test commands here
        python app.py
