name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Echo API_KEY
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "API Key: $API_KEY"
          # Or list all environment variables
          env | grep API_KEY

      - name: Deploy application
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: |
          python app.py  # Replace with your deployment command
